### PR TITLE
Some issues on Gregtania6

### PR DESCRIPTION
**Pull request by IconLivin**
Hi. I tried to play your techpack named Gregtania6 on patch 1.1.4 and found out that there is some kind of a bug. On the first age at quest number 16 I crafted a hammer according a recipe on the quest, but it actually doesn't work. So I can't get further because of this quest. Write me back how can I deal with this   bug, and where i can text you normally, it's weird to have a conversation on github. Best wishes!

### CODE REVIEW

**Comment by IconLivin** [comment]
I also found another bug: if crush an axe while chopping a tree, game crushes with the following crash report
---- Minecraft Crash Report ----
// Don't do that.

Time: 8/31/19 3:38 AM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 41, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:206)
	at invtweaks.forge.ClientProxy.slotClick(ClientProxy.java:94)
	at invtweaks.InvTweaksContainerManager.click(InvTweaksContainerManager.java:266)
	at invtweaks.InvTweaksContainerManager.leftClick(InvTweaksContainerManager.java:253)
	at invtweaks.InvTweaksContainerManager.move(InvTweaksContainerManager.java:144)
	at invtweaks.InvTweaksContainerSectionManager.move(InvTweaksContainerSectionManager.java:41)
	at invtweaks.InvTweaksHandlerAutoRefill$1.run(InvTweaksHandlerAutoRefill.java:195)
	at invtweaks.InvTweaks$1.run(InvTweaks.java:122)
	at invtweaks.InvTweaks.onTick(InvTweaks.java:479)
	at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:132)
	at invtweaks.forge.ForgeClientTick.onTick(ForgeClientTick.java:24)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_367_ForgeClientTick_onTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:206)
	at invtweaks.forge.ClientProxy.slotClick(ClientProxy.java:94)
	at invtweaks.InvTweaksContainerManager.click(InvTweaksContainerManager.java:266)
	at invtweaks.InvTweaksContainerManager.leftClick(InvTweaksContainerManager.java:253)
	at invtweaks.InvTweaksContainerManager.move(InvTweaksContainerManager.java:144)
	at invtweaks.InvTweaksContainerSectionManager.move(InvTweaksContainerSectionManager.java:41)
	at invtweaks.InvTweaksHandlerAutoRefill$1.run(InvTweaksHandlerAutoRefill.java:195)
	at invtweaks.InvTweaks$1.run(InvTweaks.java:122)
	at invtweaks.InvTweaks.onTick(InvTweaks.java:479)
	at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:132)
	at invtweaks.forge.ForgeClientTick.onTick(ForgeClientTick.java:24)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_367_ForgeClientTick_onTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Liethaine'/3, l='MpServer', x=-638.69, y=87.62, z=57.67]]
	Chunk stats: MultiplayerChunkCache: 3782, 3782
	Level seed: 0
	Level generator: ID 04 - botania-skyblock, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-636,86,54), Chunk: (at 4,5,6 in -40,3; contains blocks -640,0,48 to -625,255,63), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 70805 game time, 70805 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 4 total; [EntityClientPlayerMP['Liethaine'/3, l='MpServer', x=-638.69, y=87.62, z=57.67], p['unknown'/5, l='MpServer', x=0.00, y=0.00, z=0.00], EntityItem['item.tile.log.oak'/94854, l='MpServer', x=-638.19, y=86.13, z=55.75], EntityItem['item.tile.log.oak'/95324, l='MpServer', x=-638.17, y=86.82, z=54.39]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 166383328 bytes (158 MB) / 1353711616 bytes (1291 MB) up to 5726797824 bytes (5461 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 2 loaded mod(s)
          - VoxelMap version 1.7.0
          - Mouse Tweaks version 2.4.4
	LaunchWrapper: 39 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: usernameak.fastlangmod.asm.FastLangClassTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: fi.dy.masa.itemscroller.asm.GuiScreenTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: bre.smoothfont.asm.Transformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: me.guichaguri.betterfps.transformers.MathTransformer
          - Transformer: me.guichaguri.betterfps.transformers.EventTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: com.brandon3055.brandonscore.asm.ClassTransformer
          - Transformer: lumien.resourceloader.asm.ClassTransformer
          - Transformer: bre.nti.tweaker.Transformer
          - Transformer: com.enderio.core.common.transform.EnderCoreTransformer
          - Transformer: com.enderio.core.common.transform.EnderCoreTransformerClient
          - Transformer: fastcraft.J
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	itemscroller-coremod{0.12.0-alpha.1} [Item Scroller CoreMod] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{2.0.3} [Not Enough Items] (NotEnoughItems-1.7.10-2.0.3-universal.jar) 
	UCHIJAAAA	smoothfontcore{1.7.10-1.15.1} [Smooth Font Core] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	smoothfont{1.7.10-1.15.3} [Smooth Font] (SmoothFont-1.7.10-1.15.3.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UCHIJAAAA	gregapi{GT6-MC1710} [Greg-API] (gregtech_1.7.10-6.11.05.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	betterquesting{3.0.306} [Better Questing] (BetterQuesting-3.0.306.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.7.10-3.0.13.jar) 
	UCHIJAAAA	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
	UCHIJAAAA	defaultworldgenerator{0.1-b13} [Default World Generator] (DefaultWorldGenerator-1.7.10-0.1-b13-universal.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	FTBL{1.0.18.2} [FTBLib] (FTBLib-1.7.10-1.0.18.3.jar) 
	UCHIJAAAA	FTBU{1.0.18.2} [FTBUtilities] (FTBUtilities-1.7.10-1.0.18.3.jar) 
	UCHIJAAAA	GardenOfGlass{sqrt(-1)} [Garden of Glass] (GardenOfGlass.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	gregapi_post{GT6-MC1710} [Greg-API-Post] (gregtech_1.7.10-6.11.05.jar) 
	UCHIJAAAA	gregtech{GT6-MC1710} [GregTech] (gregtech_1.7.10-6.11.05.jar) 
	UCHIJAAAA	HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.6.jar) 
	UCHIJAAAA	HoloInventory{1.9.1.124} [HoloInventory] (HoloInventory-1.7.10-1.9.1.124.jar) 
	UCHIJAAAA	itemscroller{0.12.0-alpha.1} [Item Scroller] (itemscroller-1.7.10-0.12.0-alpha.1.jar) 
	UCHIJAAAA	itlt{0.0.8} [It's the little things] (itlt-1.7.10-0.0.8.jar) 
	UCHIJAAAA	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UCHIJAAAA	Morpheus{1.7.10-1.6.21} [Morpheus] (Morpheus-1.7.10-1.6.21.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAAAA	MTUtils{1.6} [MTUtils] (MTUtils-1.6.jar) 
	UCHIJAAAA	questbook{2.1.1-1.7.10} [Better Questing Quest Book] (questbook-2.1.1-1.7.10.jar) 
	UCHIJAAAA	reauth{3.5.0} [ReAuth] (ReAuth-3.5.0.jar) 
	UCHIJAAAA	ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
	UCHIJAAAA	bq_standard{3.0.162} [Standard Expansion] (StandardExpansion-3.0.162.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	wailaplugins{MC1.7.10-0.2.0-25} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-25.jar) 
	UCHIJAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCHIJAAAA	gregtania{0.0.2} [Gregtania] (Gregtania-6.0.7.jar) 
	UCHIJAAAA	gtneioreplugin{1.0.5b} [GT6 NEI Ore Plugin] (GT6NEIOrePlugin-1.7.10-1.0.5b.jar) 
	UCHIJAAAA	ifu{2.0} [I Will Find You] (IFU-2.0.jar) 
	UCHIJAAAA	ItemDelocalizer{1.7.10-0.5.1b} [Item Delocalizer] (ItemDelocalizer-1.7.10-0.5.1b.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13397 Compatibility Profile Context 15.200.1055.0' Renderer: 'AMD Radeon HD 7470'
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7470 GL version 4.5.13397 Compatibility Profile Context 15.200.1055.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by monatann** [comment]
Thank you for report.

BetterQuesting bug is caused by not ignoring NBT tag.
I'll fix it in next version.

Tree issue is related to Inventry Tweaks, but I don't know why it happens.
Is it repeat-able issue? In my environment I can't find out this issue.

**Comment by IconLivin** [comment]
> Thank you for report.
> 
> BetterQuesting bug is caused by not ignoring NBT tag.
> I'll fix it in next version.
> 
> Tree issue is related to Inventry Tweaks, but I don't know why it happens.
> Is it repeat-able issue? In my environment I can't find out this issue.

**Comment by IconLivin** [comment]
I downloaded a new version 1.1.5. So the bug with the tree is unrepeatable, but the hammer bug is still there, so I keep waiting for a solution. Thank you.

**Comment by monatann** [comment]
That's strange, have you tried to use refresh command? (These command can be fired in Tier0 command block quests)
/bq_user refresh
And in some case need this command.
/bq_admin default load

I'll try again while waiting your reply:)

**Comment by IconLivin** [comment]
That's it, the second one actually worked. Thank's!

**Comment by monatann** [comment]
Ah, great.!
Thank you for reporting issues and playing, have fun :)

**Comment by IconLivin** [comment]
Thank's :)

**Comment by IconLivin** [comment]
Sorry for annoying you again. I am stucked at quest number 25. It says that i can make useful botania flowers. It says to scoop a water by bowl and throw items and  a seed, so i scooped a water like it says, and can't figure it out, to throw that and there and which items, i got a seed, i got a bowl of water, so what next? Sorry again :(

**Comment by monatann** [comment]
Petal Apothecary is used for next quests.
Pure Daisy(#26), Daybloom(#34), Nightshade(#33)

Click Petal Apothecary with Bowl of Water for filling water and throw items, then throw seed and get result item.

**Comment by monatann** [comment]
image

**Comment by IconLivin** [comment]
Yes,but petal apothecary need this flowers for craft, I accidentally found out that if you click with floral fertilizer on the grass it spawns those flowers, so now I am able to craft this petal.

**Comment by monatann** [comment]
image
image
image

Yes, you need to make floral fertilizer, there is living root in your island.
Of course you can use Bone Meal and get flower dye for making this. 
I think you have cleared floral fertilizer#19 quest...

**Pull request closed without merging**
